name: ovnmon-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        export GOPATH=$(go env GOPATH)
        make

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.40.1

